### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by amakvana** [theboy181/switch-ptchtxt-mods#15]
Hi Jason,

Hope you're well! I'm the dev of YuzuModDownloader (YMD). 

I was wondering, with your permission of course, if it's possible in the next version of YMD, I could also use this repository as an additional mirror to download Switch-Mods for Yuzu? As the official repo hasn't been updated since September and you're a major contributor to it. 

This is my thought trail to integrate this repo:

1. Have an dropdown within YMD allowing the user to select a download server. 
2. Create a couple of xml files that replicates how you structure your mod directories within this repo, key-value pairing it with TitleID's 
3. Pull the xml from my repo, scan against games library, find the mods and download them directly off your repo via direct url paths.

A mock-up I've got so far looks like this:
![image](https://user-images.githubusercontent.com/66264136/207282838-75f84a2c-5b47-4bdf-a8b2-9c557d5fed26.png)

Full credit and acknowledgements would be added within my YMD repo, linking you and here.

Let me know what you think.

Cheers!

**Comment by theboy181** [comment]
Sounds good! Would I be able to opt out at any time?
________________________________
From: Akash Makvana ***@***.***>
Sent: December 13, 2022 2:59 AM
To: theboy181/switch-ptchtxt-mods ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [theboy181/switch-ptchtxt-mods] Request (Issue #15)


Hi Jason,

Hope you're well! I'm the dev of YuzuModDownloader (YMD).

I was wondering, with your permission of course, if it's possible in the next version of YMD, I could also use this repository as an additional mirror to download Switch-Mods for Yuzu? As the official repo hasn't been updated since September and you're a major contributor to it.

This is my thought trail to integrate this repo:

  1.  Have an dropdown within YMD allowing the user to select a download server.
  2.  Create a couple of xml files that replicates how you structure your mod directories within this repo, key-value pairing it with TitleID's
  3.  Pull the xml from my repo, scan against games library, find the mods and download them directly off your repo via direct url paths.

A mock-up I've got so far looks like this:
[image]<https://user-images.githubusercontent.com/66264136/207282838-75f84a2c-5b47-4bdf-a8b2-9c557d5fed26.png>

Full credit and acknowledgements would be added within my YMD repo, linking you and here.

Let me know what you think.

Cheers!

**Comment by amakvana** [comment]
> Sounds good! 

Thank you very much, it's appreciated mate.

>Would I be able to opt out at any time?

Sure, you'd have to give me a bit of time to push an update to do this but I don't see why not. I do know that having your repo available would benefit all users of YMD massively and increase exposure to your repo too

I will keep this "Issue" left as Open and once I push the next version, I will come back and close this, if that works for you?

**Comment by amakvana** [comment]
Closed - Added to YuzuModDownloader v1.3.0.0
https://github.com/amakvana/YuzuModDownloader/releases/latest
